name: Workflow CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Pods
      run: pod install
    - name: xcodebuild clean
      run: swift test -v
    - name: build project
      run: xcodebuild build -workspace my-pet.xcworkspace -scheme my-pet -destination "platform=iOS Simulator,OS=13.5,name=iPhone 11"

